/* ASTRAL VANGUARD — art.js
 * Procedural mech-SF sprite generation (offscreen canvases) + optional PNG asset
 * override + particle / explosion / effects engine.
 */
(function (global) {
  'use strict';
  const AV = global.AV;
  const U = AV.U;

  function mk(w, h) { const c = document.createElement('canvas'); c.width = w; c.height = h; return c; }

  /* ----------------------------------------------------------------- *
   * Art : sprite cache, procedural builders, PNG override
   * ----------------------------------------------------------------- */
  const Art = AV.Art = {
    sprites: Object.create(null),
    usingImages: false,

    get(name) { return this.sprites[name]; },

    // Attempt to load real PNG assets generated by tools/gen_assets.mjs.
    // Silently falls back to procedural art if unavailable (file:// or missing).
    async loadAssets() {
      try {
        const res = await fetch('assets/manifest.json', { cache: 'no-cache' });
        if (!res.ok) return false;
        const man = await res.json();
        const entries = Object.entries(man.sprites || {});
        let loaded = 0;
        await Promise.all(entries.map(([name, file]) => new Promise((resolve) => {
          const img = new Image();
          img.onload = () => { this.sprites[name] = img; loaded++; resolve(); };
          img.onerror = () => resolve();
          img.src = 'assets/' + file;
        })));
        if (loaded > 0) { this.usingImages = true; console.log('[AV] Loaded ' + loaded + ' image assets'); return true; }
      } catch (e) { /* fall through to procedural */ }
      return false;
    },

    /* ---- shared drawing helpers ---- */
    _metal(ctx, x, y, w, h, c1, c2, c3) {
      const g = ctx.createLinearGradient(x, y, x, y + h);
      g.addColorStop(0, c1); g.addColorStop(0.45, c2); g.addColorStop(0.55, c3 || c2); g.addColorStop(1, c1);
      return g;
    },
    _panelLines(ctx, pts, color) {
      ctx.strokeStyle = color; ctx.lineWidth = 1; ctx.globalAlpha = 0.5;
      ctx.beginPath(); pts.forEach((p, i) => (i ? ctx.lineTo(p[0], p[1]) : ctx.moveTo(p[0], p[1]))); ctx.stroke();
      ctx.globalAlpha = 1;
    },

    buildProcedural() {
      this._player();
      this._option();
      this._enemy('scout', '#8fa', '#2a6', 1);
      this._enemy('fighter', '#9bf', '#246', 1.25);
      this._enemy('hunter', '#fb8', '#722', 1.1);
      this._enemy('turret', '#bbc', '#445', 1.0);
      this._dropper();
      this._presser();
      this._mine();
      this._rock();
      this._capsule();
      this._bossCore();
      this._bossPanel();
      this._bossTurret();
    },

    _player() {
      const c = mk(72, 48), x = c.getContext('2d'); const cx = 0, cy = 24;
      // engine glow at rear handled in-engine; draw hull pointing right
      x.save();
      // main fuselage
      const body = this._metal(x, 8, 12, 56, 24, '#5b6675', '#cfe0f2', '#8fa0b4');
      x.fillStyle = body;
      x.beginPath();
      x.moveTo(70, 24); x.lineTo(40, 14); x.lineTo(8, 16); x.quadraticCurveTo(2, 24, 8, 32);
      x.lineTo(40, 34); x.closePath(); x.fill();
      // wings
      x.fillStyle = '#41506a';
      x.beginPath(); x.moveTo(34, 18); x.lineTo(16, 2); x.lineTo(26, 18); x.closePath(); x.fill();
      x.beginPath(); x.moveTo(34, 30); x.lineTo(16, 46); x.lineTo(26, 30); x.closePath(); x.fill();
      // wing accents
      x.fillStyle = '#ff7a3c';
      x.fillRect(18, 4, 6, 2); x.fillRect(18, 42, 6, 2);
      // canopy
      const g = x.createLinearGradient(40, 18, 56, 26); g.addColorStop(0, '#bff'); g.addColorStop(1, '#069');
      x.fillStyle = g; x.beginPath(); x.moveTo(52, 24); x.lineTo(44, 19); x.lineTo(38, 24); x.lineTo(44, 28); x.closePath(); x.fill();
      // nose tip
      x.fillStyle = '#ffd24a'; x.beginPath(); x.moveTo(70, 24); x.lineTo(62, 21); x.lineTo(62, 27); x.closePath(); x.fill();
      // panel detail
      this._panelLines(x, [[20, 20], [44, 21], [44, 27], [20, 28]], '#1b2433');
      // intake glow
      x.fillStyle = '#3df'; x.globalAlpha = 0.8; x.fillRect(10, 22, 3, 4); x.globalAlpha = 1;
      x.restore();
      c.ax = 70; c.ay = 24; // anchor (nose) for muzzle
      this.sprites.player = c;
    },

    _option() {
      const c = mk(22, 22), x = c.getContext('2d');
      const g = x.createRadialGradient(11, 11, 1, 11, 11, 11); g.addColorStop(0, '#bff'); g.addColorStop(0.5, '#39d'); g.addColorStop(1, '#114');
      x.fillStyle = g; x.beginPath(); x.arc(11, 11, 9, 0, U.TAU); x.fill();
      x.strokeStyle = '#7ef'; x.lineWidth = 1.5; x.beginPath(); x.arc(11, 11, 9, 0, U.TAU); x.stroke();
      x.fillStyle = '#fff'; x.beginPath(); x.arc(11, 11, 3, 0, U.TAU); x.fill();
      this.sprites.option = c;
    },

    _enemy(name, hi, lo, scale) {
      const w = Math.round(48 * scale), h = Math.round(40 * scale), c = mk(w, h), x = c.getContext('2d');
      x.scale(scale, scale);
      // hull pointing left (enemies face the player on the left)
      const body = this._metal(x, 6, 8, 36, 48, lo, hi, '#fff');
      x.fillStyle = body;
      x.beginPath();
      x.moveTo(2, 20); x.lineTo(30, 8); x.lineTo(44, 14); x.quadraticCurveTo(48, 20, 44, 26);
      x.lineTo(30, 32); x.closePath(); x.fill();
      // fins
      x.fillStyle = lo;
      x.beginPath(); x.moveTo(34, 10); x.lineTo(46, 2); x.lineTo(40, 12); x.closePath(); x.fill();
      x.beginPath(); x.moveTo(34, 30); x.lineTo(46, 38); x.lineTo(40, 28); x.closePath(); x.fill();
      // eye / core
      const g = x.createRadialGradient(14, 20, 1, 14, 20, 7); g.addColorStop(0, '#fff'); g.addColorStop(0.4, '#f33'); g.addColorStop(1, '#400');
      x.fillStyle = g; x.beginPath(); x.arc(14, 20, 5, 0, U.TAU); x.fill();
      this._panelLines(x, [[20, 14], [40, 16], [40, 24], [20, 26]], '#0008');
      c.core = { x: 14 * scale, y: 20 * scale };
      this.sprites[name] = c;
    },

    _dropper() {
      const c = mk(40, 44), x = c.getContext('2d');
      x.fillStyle = this._metal(x, 4, 2, 32, 26, '#3a4452', '#aeb8c6', '#6b7585');
      x.beginPath(); x.moveTo(6, 6); x.lineTo(34, 6); x.lineTo(30, 24); x.lineTo(10, 24); x.closePath(); x.fill();
      x.fillStyle = '#222a36'; x.fillRect(12, 24, 16, 14);
      x.fillStyle = '#ff5a2c'; x.fillRect(14, 36, 12, 4); // hatch
      x.fillStyle = '#7ef'; x.beginPath(); x.arc(20, 13, 4, 0, U.TAU); x.fill();
      this.sprites.dropper = c;
    },

    _presser() {
      const c = mk(96, 120), x = c.getContext('2d');
      x.fillStyle = this._metal(x, 0, 0, 96, 30, '#2b323d', '#9aa6b6', '#566273');
      x.fillRect(0, 0, 96, 30);
      x.fillStyle = '#1b2029'; for (let i = 8; i < 96; i += 16) x.fillRect(i, 30, 8, 70);
      x.fillStyle = this._metal(x, 0, 96, 96, 24, '#1b2029', '#ffb347', '#7a4a12');
      x.fillRect(0, 96, 96, 24);
      x.fillStyle = '#ffdd55'; for (let i = 4; i < 96; i += 12) { x.beginPath(); x.moveTo(i, 96); x.lineTo(i + 6, 96); x.lineTo(i + 3, 104); x.closePath(); x.fill(); }
      this.sprites.presser = c;
    },

    _mine() {
      const c = mk(28, 28), x = c.getContext('2d');
      const g = x.createRadialGradient(14, 14, 2, 14, 14, 12); g.addColorStop(0, '#fdd'); g.addColorStop(0.4, '#c33'); g.addColorStop(1, '#300');
      x.fillStyle = g; x.beginPath(); x.arc(14, 14, 9, 0, U.TAU); x.fill();
      x.strokeStyle = '#fa0'; x.lineWidth = 2;
      for (let a = 0; a < U.TAU; a += U.TAU / 8) { x.beginPath(); x.moveTo(14 + Math.cos(a) * 8, 14 + Math.sin(a) * 8); x.lineTo(14 + Math.cos(a) * 13, 14 + Math.sin(a) * 13); x.stroke(); }
      this.sprites.mine = c;
    },

    _rock() {
      const c = mk(48, 48), x = c.getContext('2d');
      const g = x.createRadialGradient(18, 16, 4, 24, 24, 26); g.addColorStop(0, '#7a6a5a'); g.addColorStop(0.6, '#4a3f36'); g.addColorStop(1, '#241d18');
      x.fillStyle = g; x.beginPath();
      const pts = 9; for (let i = 0; i < pts; i++) { const a = i / pts * U.TAU, r = 18 + Math.sin(i * 2.3) * 5; const px = 24 + Math.cos(a) * r, py = 24 + Math.sin(a) * r; i ? x.lineTo(px, py) : x.moveTo(px, py); }
      x.closePath(); x.fill();
      x.strokeStyle = '#1a140f'; x.lineWidth = 1.5; x.globalAlpha = 0.6;
      x.beginPath(); x.moveTo(14, 18); x.lineTo(26, 24); x.lineTo(20, 34); x.stroke();
      x.fillStyle = '#ff6a2a'; x.globalAlpha = 0.5; x.beginPath(); x.arc(30, 18, 3, 0, U.TAU); x.fill(); x.globalAlpha = 1;
      this.sprites.debris = c;
    },

    _capsule() {
      const c = mk(28, 28), x = c.getContext('2d');
      // bright red Gradius-style capsule
      const g = x.createLinearGradient(0, 4, 0, 24); g.addColorStop(0, '#ff9a9a'); g.addColorStop(0.5, '#ff2b2b'); g.addColorStop(1, '#900');
      x.fillStyle = g; x.strokeStyle = '#fff'; x.lineWidth = 2;
      const r = 7; x.beginPath();
      x.moveTo(6, 8); x.lineTo(22, 8); x.arcTo(24, 8, 24, 10, r); x.lineTo(24, 18); x.arcTo(24, 20, 22, 20, r);
      x.lineTo(6, 20); x.arcTo(4, 20, 4, 18, r); x.lineTo(4, 10); x.arcTo(4, 8, 6, 8, r); x.closePath(); x.fill(); x.stroke();
      x.fillStyle = '#fff'; x.font = 'bold 11px monospace'; x.textAlign = 'center'; x.fillText('P', 14, 18);
      this.sprites.capsule = c;
      // fake capsule (looks similar but tinted, glitchy) — initial-death gimmick
      const f = mk(28, 28), fx = f.getContext('2d');
      fx.drawImage(c, 0, 0); fx.globalCompositeOperation = 'source-atop';
      fx.fillStyle = 'rgba(120,40,160,0.55)'; fx.fillRect(0, 0, 28, 28);
      this.sprites.capsuleFake = f;
    },

    _bossCore() {
      const c = mk(80, 80), x = c.getContext('2d');
      const g = x.createRadialGradient(40, 40, 4, 40, 40, 38); g.addColorStop(0, '#fff'); g.addColorStop(0.3, '#3ef'); g.addColorStop(0.7, '#08a'); g.addColorStop(1, '#024');
      x.fillStyle = g; x.beginPath(); x.arc(40, 40, 34, 0, U.TAU); x.fill();
      x.strokeStyle = '#bff'; x.lineWidth = 3; x.beginPath(); x.arc(40, 40, 34, 0, U.TAU); x.stroke();
      x.strokeStyle = '#0ff'; x.lineWidth = 2;
      for (let i = 0; i < 6; i++) { const a = i / 6 * U.TAU; x.beginPath(); x.moveTo(40, 40); x.lineTo(40 + Math.cos(a) * 30, 40 + Math.sin(a) * 30); x.stroke(); }
      x.fillStyle = '#fff'; x.beginPath(); x.arc(40, 40, 8, 0, U.TAU); x.fill();
      this.sprites.bossCore = c;
    },
    _bossPanel() {
      const c = mk(120, 200), x = c.getContext('2d');
      x.fillStyle = this._metal(x, 0, 0, 120, 200, '#2a3340', '#8693a6', '#4a5666');
      x.beginPath(); x.moveTo(120, 0); x.lineTo(30, 20); x.quadraticCurveTo(0, 100, 30, 180); x.lineTo(120, 200); x.closePath(); x.fill();
      x.fillStyle = '#1a212b'; for (let yy = 24; yy < 180; yy += 28) x.fillRect(34, yy, 80, 14);
      x.fillStyle = '#ff7a3c'; x.fillRect(30, 96, 90, 8);
      x.strokeStyle = '#0009'; x.lineWidth = 2; x.beginPath(); x.moveTo(40, 16); x.quadraticCurveTo(10, 100, 40, 184); x.stroke();
      this.sprites.bossPanel = c;
    },
    _bossTurret() {
      const c = mk(44, 44), x = c.getContext('2d');
      const g = x.createRadialGradient(22, 22, 2, 22, 22, 20); g.addColorStop(0, '#cdd8e6'); g.addColorStop(1, '#39424f');
      x.fillStyle = g; x.beginPath(); x.arc(22, 22, 18, 0, U.TAU); x.fill();
      x.fillStyle = '#1c2230'; x.fillRect(0, 18, 22, 8);
      x.fillStyle = '#f55'; x.beginPath(); x.arc(22, 22, 5, 0, U.TAU); x.fill();
      this.sprites.bossTurret = c;
    },
  };

  /* ----------------------------------------------------------------- *
   * Particles / Effects
   * ----------------------------------------------------------------- */
  const FX = AV.FX = {
    parts: [],
    rings: [],

    clear() { this.parts.length = 0; this.rings.length = 0; },

    spawn(p) { this.parts.push(p); },

    spark(x, y, n, color, spd) {
      for (let i = 0; i < n; i++) {
        const a = U.rand(0, U.TAU), s = U.rand(spd * 0.3, spd);
        this.parts.push({ t: 'spark', x, y, vx: Math.cos(a) * s, vy: Math.sin(a) * s, life: U.rand(0.2, 0.5), max: 0.5, col: color || '#ffd86b', r: U.rand(1, 2.4) });
      }
    },
    smoke(x, y, n, vx, vy) {
      for (let i = 0; i < n; i++) this.parts.push({ t: 'smoke', x: x + U.rand(-3, 3), y: y + U.rand(-3, 3), vx: (vx || 0) + U.rand(-12, 12), vy: (vy || 0) + U.rand(-12, 12), life: U.rand(0.5, 1.1), max: 1.1, r: U.rand(3, 7), grow: U.rand(18, 40) });
    },
    fire(x, y, n, dir) {
      for (let i = 0; i < n; i++) this.parts.push({ t: 'fire', x, y, vx: (dir || 0) * U.rand(20, 80) + U.rand(-20, 20), vy: U.rand(-30, 30), life: U.rand(0.15, 0.35), max: 0.35, r: U.rand(2.5, 5) });
    },
    debris(x, y, n, color) {
      for (let i = 0; i < n; i++) { const a = U.rand(0, U.TAU), s = U.rand(60, 260); this.parts.push({ t: 'debris', x, y, vx: Math.cos(a) * s, vy: Math.sin(a) * s, life: U.rand(0.4, 0.9), max: 0.9, r: U.rand(1.5, 3.5), col: color || '#cfd6e0', spin: U.rand(-10, 10), rot: 0, vyG: 240 }); }
    },
    ring(x, y, color, max, lw) { this.rings.push({ x, y, r: 2, max: max || 70, life: 0.45, t0: 0.45, col: color || '#bff', lw: lw || 4 }); },

    muzzle(x, y, color) {
      this.parts.push({ t: 'flash', x, y, life: 0.08, max: 0.08, r: 14, col: color || '#ffeaa0' });
      this.fire(x, y, 3, 1);
    },

    explosion(x, y, scale) {
      scale = scale || 1;
      this.parts.push({ t: 'flash', x, y, life: 0.12, max: 0.12, r: 26 * scale, col: '#fff' });
      this.ring(x, y, '#ffd27a', 60 * scale, 4 * scale);
      this.ring(x, y, '#ff6a2a', 38 * scale, 3 * scale);
      for (let i = 0; i < 14 * scale; i++) { const a = U.rand(0, U.TAU), s = U.rand(40, 220) * scale; this.parts.push({ t: 'fireball', x, y, vx: Math.cos(a) * s, vy: Math.sin(a) * s, life: U.rand(0.3, 0.6), max: 0.6, r: U.rand(4, 10) * scale }); }
      this.debris(x, y, 10 * scale, '#cfd6e0');
      this.smoke(x, y, 8 * scale);
      this.spark(x, y, 12 * scale, '#ffd86b', 280);
    },

    bigExplosion(x, y) {
      for (let k = 0; k < 6; k++) setTimeoutFX(() => this.explosion(x + U.rand(-40, 40), y + U.rand(-40, 40), U.rand(1.0, 1.8)), k * 90);
      this.ring(x, y, '#fff', 200, 8); this.ring(x, y, '#ff8a3a', 150, 6);
    },

    update(dt) {
      const ps = this.parts;
      for (let i = ps.length - 1; i >= 0; i--) {
        const p = ps[i]; p.life -= dt;
        if (p.life <= 0) { ps.splice(i, 1); continue; }
        p.x += (p.vx || 0) * dt; p.y += (p.vy || 0) * dt;
        if (p.t === 'smoke') { p.r += p.grow * dt; p.vx *= 0.94; p.vy *= 0.94; }
        else if (p.t === 'fireball') { p.r += 18 * dt; p.vx *= 0.9; p.vy *= 0.9; }
        else if (p.t === 'debris') { p.vy += p.vyG * dt; p.rot += p.spin * dt; }
        else if (p.t === 'spark' || p.t === 'fire') { p.vx *= 0.92; p.vy *= 0.92; }
      }
      const rs = this.rings;
      for (let i = rs.length - 1; i >= 0; i--) { const r = rs[i]; r.life -= dt; if (r.life <= 0) { rs.splice(i, 1); continue; } r.r = U.lerp(r.max, r.r, 0); r.r += (r.max - r.r) * Math.min(1, dt * 10); }
    },

    draw(ctx) {
      ctx.save();
      // additive glow layer
      ctx.globalCompositeOperation = 'lighter';
      for (const p of this.parts) {
        const k = p.life / p.max;
        if (p.t === 'spark') {
          ctx.globalAlpha = k; ctx.fillStyle = p.col;
          ctx.beginPath(); ctx.arc(p.x, p.y, p.r * k, 0, U.TAU); ctx.fill();
        } else if (p.t === 'fire') {
          ctx.globalAlpha = k * 0.9; const g = ctx.createRadialGradient(p.x, p.y, 0, p.x, p.y, p.r * 2);
          g.addColorStop(0, '#fff'); g.addColorStop(0.4, '#ffb13a'); g.addColorStop(1, 'rgba(255,60,0,0)');
          ctx.fillStyle = g; ctx.beginPath(); ctx.arc(p.x, p.y, p.r * 2, 0, U.TAU); ctx.fill();
        } else if (p.t === 'fireball') {
          ctx.globalAlpha = k; const g = ctx.createRadialGradient(p.x, p.y, 0, p.x, p.y, p.r);
          g.addColorStop(0, '#fff'); g.addColorStop(0.35, '#ffd24a'); g.addColorStop(0.7, '#ff5a1e'); g.addColorStop(1, 'rgba(120,0,0,0)');
          ctx.fillStyle = g; ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, U.TAU); ctx.fill();
        } else if (p.t === 'flash') {
          ctx.globalAlpha = k; const g = ctx.createRadialGradient(p.x, p.y, 0, p.x, p.y, p.r);
          g.addColorStop(0, '#fff'); g.addColorStop(0.6, p.col); g.addColorStop(1, 'rgba(255,255,255,0)');
          ctx.fillStyle = g; ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, U.TAU); ctx.fill();
        }
      }
      for (const r of this.rings) {
        const k = r.life / r.t0; ctx.globalAlpha = k; ctx.strokeStyle = r.col; ctx.lineWidth = r.lw * k;
        ctx.beginPath(); ctx.arc(r.x, r.y, r.r, 0, U.TAU); ctx.stroke();
      }
      // normal blend layer (smoke, debris)
      ctx.globalCompositeOperation = 'source-over';
      for (const p of this.parts) {
        const k = p.life / p.max;
        if (p.t === 'smoke') {
          ctx.globalAlpha = k * 0.4; const g = ctx.createRadialGradient(p.x, p.y, 0, p.x, p.y, p.r);
          g.addColorStop(0, 'rgba(80,80,90,0.9)'); g.addColorStop(1, 'rgba(40,40,50,0)');
          ctx.fillStyle = g; ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, U.TAU); ctx.fill();
        } else if (p.t === 'debris') {
          ctx.globalAlpha = k; ctx.fillStyle = p.col; ctx.save(); ctx.translate(p.x, p.y); ctx.rotate(p.rot);
          ctx.fillRect(-p.r, -p.r * 0.5, p.r * 2, p.r); ctx.restore();
        }
      }
      ctx.restore();
    },
  };

  // tiny setTimeout wrapper so staged explosions don't fire if game resets
  let _fxToken = 0;
  function setTimeoutFX(fn, ms) { const tk = _fxToken; setTimeout(() => { if (tk === _fxToken) fn(); }, ms); }
  FX.resetTimers = () => { _fxToken++; };

})(window);
